### ISSUE TITLE
Global Name "Polygon"

### ISSUE THREAD

**Issue by herleeyandi** [kylesf/Advanced-Lane-Detection#1]
Hello after running in part test I got this error, how you solve that?
`---------------------------------------------------------------------------`
`NameError                                 Traceback (most recent call last)`
`<ipython-input-18-6e0650b9d07c> in <module>()`
`     35 # Run pipline on images`
`     36 `
`---> 37 Image_1 = pipeline(image_1, mtx, dist, dash)`
`     38 Image_2 = pipeline(image_2, mtx, dist, dash)`
`     39 Image_3 = pipeline(image_3, mtx, dist, dash)`
``
`<ipython-input-15-c8608f53ad44> in pipeline(image, mtx, dist, dash)`
`    199         print ("Error in something?")`
`    200 `
`--> 201         result = cv2.addWeighted(undist, 1, polygon, 0.3, 0)`
`    202 `
`    203         original = undist.copy()`
``
`NameError: global name 'polygon' is not defined`

**Comment by kylesf** [comment]
Run the cell where the global variable polygon is defined and make sure IMAGE = True.

**Comment by herleeyandi** [comment]
I just run the cell which contains function 'pipeline' it define polygons as global, but not initialize it.
What you mean by IMAGE= true? Is it means I must check whether the image successfully loaded?

**Comment by kylesf** [comment]
Once the global is defined it will stay active in your python kernel. IMAGE = True is a flag for processing the images and not the video. Makes a difference as you track frames for a video.

**Comment by frankzl** [comment]
I had the same problem as you heyleeyandi! I think Jupyter was not able to understand the list comprehension.

I replaced these lines in the function lane_curve:
y  = [x * (30/720.) for x in left_line[1]]
Instead:
y = []
for item in left_line[1]:
    y.append(item*(30/720.))

There were some other errors after I replaced those lines, but I managed to get it running. It's really nice!

**Comment by kanishk-nd** [comment]
@frankzl I am running into same issue, even after making the fix you suggested:
```
Traceback (most recent call last):
  File "kylesf_lane_detect.py", line 519, in <module>
    Image_1 = pipeline(image_1, mtx, dist, dash)
  File "kylesf_lane_detect.py", line 272, in pipeline
    polygon = polygon
NameError: global name 'polygon' is not defined
```
In function impose_Lane_Area(), you might have to update
`_unwarped = cv2.warpPerspective(**overlay**, M, img_size)_
`
since cv2.fillPoly doesn't returns None 

Also, After making these 2 fixes, I am running into some new issue:
`OpenCV Error: Assertion failed (contour1.checkVector(2) >= 0 && contour2.checkVector(2) >= 0 && (contour1.depth() == CV_32F || contour1.depth() == CV_32S) && contour1.depth() == contour2.depth()) in matchShapes`

Any suggestion?

**Comment by frankzl** [comment]
@kanishk-nd 
It's been a while since I last looked at the code..
I just forked the repository and commited my modifications to the ipynb file for you. I only changed very little in the code. I tried running it again and the algorithm works on given the pictures.
Try it out and see if it works on your machine :)

**Comment by kanishk-nd** [comment]
@frankzl Thanks !! ^_^

I dumped the code in to a .py script, and realised that issue is with the Exception block (main exception block in pipeline() )which doesn't receive the 'polygon' variable. So I tweaked the code to not hit the last exception block for now. 
You fixes work, as they also don't hit this Exception handler
